### PR TITLE
Save memory by not accumulating input into a string

### PR DESCRIPTION
**Pull request by PetrGlad**
Reduce memory consumption while parsing requests' body JSON by not accumulating whole body in a string.

### CODE REVIEW

**Comment by PetrGlad** [comment]
I'd happy to resolve "PR's body failed check 'conta..." if I knew what it is.

**Comment by sebastianpoeplau** [comment]
👍

**Comment by sebastianpoeplau** [comment]
Thank you!

**Comment by PetrGlad** [comment]
:+1:

**Pull request merged**
