### PR TITLE
enable multipart parameters

### LINKED ISSUE #18: Support data type "file"
> An additional primitive data type `"file"` is used by the [Parameter Object](#parameterObject) and the
> [Response Object](#responseObject) to set the parameter type or the response as being a file.

### LINKED ISSUE #21: Support "multipart/form-data" for body parameters
> `multipart/form-data` - each parameter takes a section in the payload with an internal header. For example, for the header `Content-Disposition: form-data; name="submit-name"` the name of the parameter is `submit-name`. This type of form parameters is more commonly used for file transfers.

### PR DESCRIPTION
**Pull request by harti2006**
- fixes #21
- fixes #18

This Pull Request enables multipart parameters and file uploading. The `"file"` response object type is not yet supported.

### CODE REVIEW

**Comment by harti2006** [comment]
Replaced by zalando-incubator/swagger1st#3

**Comment by sebastianpoeplau** [comment]
👍

**Comment by sebastianpoeplau** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Pull request merged**
